# Generated by Django 3.1.6 on 2021-02-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altruist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
